# Import the dudes

In [26]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy as sp
import glob
import json

import seaborn as sn

import matplotlib.pyplot as plt

%matplotlib inline

In [27]:
os.chdir('C:\\Users\\Jonathan\\Desktop\\Songsdump')

In [28]:
folders = ['americas',
           'asia',
           'eur',
           'oceania',
           'uk']
root = os.getcwd()

# Go Slow

In [4]:
sub_fldr = (root + '\\' + folders[1]) 
os.chdir(sub_fldr)
json_list = glob.glob("*.json")
json_list

['Tokyo_(2018-04-13)_page-1.json',
 'Tokyo_(2018-04-14)_page-1.json',
 'Tokyo_(2018-04-15)_page-1.json',
 'Tokyo_(2018-04-16)_page-1.json',
 'Tokyo_(2018-04-17)_page-1.json',
 'Tokyo_(2018-04-18)_page-1.json',
 'Tokyo_(2018-04-19)_page-1.json',
 'Tokyo_(2018-04-21)_page-1.json',
 'Tokyo_(2018-04-22)_page-1.json']

In [5]:
json_data = json.load(open(json_list[9]))
df = pd.DataFrame(json_data['resultsPage']['results']['event'])

IndexError: list index out of range

In [6]:
df

NameError: name 'df' is not defined

In [41]:
def create_FuinkiPanda(folder = folders[1]):
    Funki_Panda = pd.DataFrame([])
    print(folder)
    print('******************')
    
    # Fetch the selected folder
    # And target that dir
    sub_fldr = (os.getcwd() + '\\' + folder)  
    os.chdir(sub_fldr)
    print(sub_fldr)
    
    # Create a list of all the .json files inside the selected folder
    json_list = glob.glob("*.json")
    
    # Then loop inside each file 
    for j in json_list:        
        test_json_file = sub_fldr + '\\' + j
        #print(test_json_file)
        
        json_data = json.load(open(test_json_file))
        
        if json_data['resultsPage']['totalEntries'] == 0:
            pass
        
        else:
            df = pd.DataFrame(json_data['resultsPage']['results']['event'])
        
            # Append the dataset
            Funki_Panda = Funki_Panda.append(df)
    
    #Funki_Panda = pd.concat(Funki_Panda, axis=1)
    result_fldr = (root + '\\CSVs')
    os.chdir(result_fldr)
    print(os.getcwd())
    
    Funki_Panda.to_csv(folder + '.csv')
    
    
    # Go back to original folder
    os.chdir(root)
    return(Funki_Panda)

In [42]:
os.chdir('C:\\Users\\Jonathan\\Desktop\\Songsdump')

In [43]:
for i in range(len(folders)):
    print(i)
    create_FuinkiPanda(folder = folders[i])

0
americas
******************
C:\Users\Jonathan\Desktop\Songsdump\americas
C:\Users\Jonathan\Desktop\Songsdump\CSVs
1
asia
******************
C:\Users\Jonathan\Desktop\Songsdump\asia
C:\Users\Jonathan\Desktop\Songsdump\CSVs
2
eur
******************
C:\Users\Jonathan\Desktop\Songsdump\eur
C:\Users\Jonathan\Desktop\Songsdump\CSVs
3
oceania
******************
C:\Users\Jonathan\Desktop\Songsdump\oceania
C:\Users\Jonathan\Desktop\Songsdump\CSVs
4
uk
******************
C:\Users\Jonathan\Desktop\Songsdump\uk
C:\Users\Jonathan\Desktop\Songsdump\CSVs

In [47]:
df = create_FuinkiPanda(folder = folders[4])

uk
******************
C:\Users\Jonathan\Desktop\Songsdump\uk
C:\Users\Jonathan\Desktop\Songsdump\CSVs

In [48]:
list(df.columns)

['ageRestriction',
 'displayName',
 'end',
 'id',
 'location',
 'performance',
 'popularity',
 'series',
 'start',
 'status',
 'type',
 'uri',
 'venue']

In [49]:
df

,ageRestriction,displayName,end,id,location,performance,popularity,series,start,status,type,uri,venue
0,None,"Ciaran Lavery at Empire Music Hall (April 13, ...",NaN,32504799,"{'city': 'Belfast, UK', 'lat': 54.5882682, 'ln...","[{'displayName': 'Ciaran Lavery', 'billingInde...",0.005217,NaN,"{'datetime': '2018-04-13T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32504799-ciar...,"{'displayName': 'Empire Music Hall', 'lat': 54..."
1,None,"Liberty Ellman Trio, Stephan Crump, Liberty El...",NaN,33192179,"{'city': 'Belfast, UK', 'lat': 54.5862571, 'ln...","[{'displayName': 'Liberty Ellman Trio', 'billi...",0.000057,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/33192179-libe...,"{'displayName': 'Crescent Arts Centre', 'lat':..."
2,18+,"Lauren Lo Sung at Thompsons Garage (April 13, ...",NaN,33374034,"{'city': 'Belfast, UK', 'lat': 54.5966443, 'ln...","[{'displayName': 'Lauren Lo Sung', 'billingInd...",0.000065,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/33374034-laur...,"{'displayName': 'Thompsons Garage', 'lat': 54...."
0,None,"The Smyths at Limelight 2 (April 14, 2018)",NaN,30963759,"{'lat': 54.5935125, 'lng': -5.9287705, 'city':...","[{'billing': 'headline', 'displayName': 'The S...",0.000341,NaN,"{'datetime': '2018-04-14T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/30963759-smyt...,"{'displayName': 'Limelight 2', 'metroArea': {'..."
1,None,"Tokio Myers at SSE Arena (April 14, 2018)",NaN,32008069,"{'city': 'Belfast, UK', 'lat': 54.6038086, 'ln...","[{'displayName': 'Tokio Myers', 'billingIndex'...",0.000039,NaN,"{'datetime': '2018-04-14T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32008069-toki...,"{'displayName': 'SSE Arena', 'lat': 54.6038086..."
2,None,"Aslan at Mandela Hall (April 14, 2018)",NaN,32658329,"{'city': 'Belfast, UK', 'lat': 54.5860497, 'ln...","[{'displayName': 'Aslan', 'billingIndex': 1, '...",0.001991,NaN,"{'datetime': '2018-04-14T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32658329-asla...,"{'displayName': 'Mandela Hall', 'lat': 54.5860..."
3,None,Daoiri Farrell at Crescent Arts Centre (April ...,NaN,33039344,"{'city': 'Belfast, UK', 'lat': 54.5862571, 'ln...","[{'displayName': 'Daoiri Farrell', 'billingInd...",0.000051,NaN,"{'datetime': '2018-04-14T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33039344-daoi...,"{'displayName': 'Crescent Arts Centre', 'lat':..."
0,Under 18's may attend with adult supervision,"Matt McGinn at Black Box (April 15, 2018)",NaN,33496284,"{'city': 'Belfast, UK', 'lat': 54.6011669, 'ln...","[{'displayName': 'Matt McGinn', 'billingIndex'...",0.000155,NaN,"{'datetime': '2018-04-15T13:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33496284-matt...,"{'displayName': 'Black Box', 'lat': 54.6011669..."
0,None,Simon James at St Louise's Comprehensive Schoo...,NaN,33531054,"{'city': 'Belfast, UK', 'lat': 54.599, 'lng': ...","[{'displayName': 'Simon James', 'billingIndex'...",0.000257,NaN,"{'datetime': '2018-04-16T09:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33531054-simo...,{'displayName': 'St Louise's Comprehensive Sch...
0,None,aston merrygold at Empire Music Hall (April 18...,NaN,32157844,"{'city': 'Belfast, UK', 'lat': 54.5882682, 'ln...","[{'displayName': 'aston merrygold', 'billingIn...",0.002053,NaN,"{'datetime': '2018-04-18T20:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32157844-asto...,"{'displayName': 'Empire Music Hall', 'lat': 54..."
1,None,Frank Turner and Frank Turner & The Sleeping S...,NaN,32658564,"{'city': 'Belfast, UK', 'lat': 54.5931969, 'ln...","[{'displayName': 'Frank Turner', 'billingIndex...",0.049869,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/32658564-fran...,"{'displayName': 'Limelight', 'lat': 54.5931969..."
2,None,"Simon James at Wallace High School (April 18, ...",NaN,33531089,"{'city': 'Lisburn, UK', 'lat': 54.5167, 'lng':...","[{'displayName': 'Simon James', 'billingIndex'...",0.000257,NaN,"{'datetime': '2018-04-18T10:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33531089-simo...,"{'displayName': 'Wallace High School', 'lat': ..."
3,None,Simon James at St Colmcille's High School (Apr...,NaN,33531099,"{'city': 'Belfast, UK', 'lat': 54.3970424, 'ln...","[{'displayName': 'Simon James', 'billingIndex'...",0.000257,NaN,"{'datetime': '2018-04-18T14:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33531099-simo...,"{'displayName': 'St Colmcille's High School', ..."
0,None,The Wonder Years at Empire Music Hall (April 1...,NaN,32743964,"{'city': 'Belfast, UK', 'lat': 54.5882682, 'ln...","[{'displayName': 'The Wonder Years', 'billingI...",0.029616,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32743964-wond...,"{'displayName': 'Empire Music Hall', 'lat': 54..."
1,None,SpringSonic 2018,"{'datetime': None, 'time': None, 'date': '2018...",33512389,"{'city': 'Belfast, UK', 'lat': 54.597285, 'lng...","[{'displayName': 'Cormac (UK)', 'billingIndex'...",0.000000,{'displayName': 'SpringSonic'},"{'datetime': None, 'time': None, 'date': '2018...",ok,Festival,http://www.songkick.com/festivals/2329599-spri...,"{'displayName': 'Unknown venue', 'lat': 54.597..."
2,None,The Low Anthem with Haley Heynderickx at Queen...,NaN,33516779,"{'city': 'Bangor, County Down, UK', 'lat': 54....","[{'displayName': 'The Low Anthem', 'billingInd...",0.019130,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33516779-low-...,{'displayName': 'Queens Parade Methodist Churc...
3,None,"Simon James at Strathearn School (April 19, 2018)",NaN,33530689,"{'city': 'Belfast, UK', 'lat': 54.599, 'lng': ...","[{'displayName': 'Simon James', 'billingIndex'...",0.000257,NaN,"{'datetime': '2018-04-19T09:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33530689-simo...,"{'displayName': 'Strathearn School', 'lat': No..."
0,None,Negative Creeps at Empire Music Hall (April 21...,NaN,31952824,"{'city': 'Belfast, UK', 'lat': 54.5882682, 'ln...","[{'displayName': 'Negative Creeps', 'billingIn...",0.000013,NaN,"{'datetime': '2018-04-21T20:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31952824-nega...,"{'displayName': 'Empire Music Hall', 'lat': 54..."
1,None,John Spillane at Hill of The O'Neill & Ranfurl...,NaN,32766854,"{'city': 'Dungannon, UK', 'lat': 54.5167, 'lng...","[{'displayName': 'John Spillane', 'billingInde...",0.000432,NaN,"{'datetime': '2018-04-21T20:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32766854-john...,{'displayName': 'Hill of The O'Neill & Ranfurl...
2,None,"Kaz Hawkins at Bardic Theatre (April 21, 2018)...",NaN,32781804,"{'city': 'Dungannon, UK', 'lat': 54.5330738, '...","[{'displayName': 'Kaz Hawkins', 'billingIndex'...",0.000052,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",cancelled,Concert,http://www.songkick.com/concerts/32781804-kaz-...,"{'displayName': 'Bardic Theatre', 'lat': 54.53..."
3,None,Prayer Storm Music with Clayton and Olivia Web...,NaN,32874619,"{'city': 'Belfast, UK', 'lat': 54.5873285, 'ln...","[{'displayName': 'Prayer Storm Music', 'billin...",0.000000,NaN,"{'datetime': '2018-04-21T12:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32874619-pray...,"{'displayName': 'UT Belfast Church', 'lat': 54..."
0,None,"Holotrop at Unknown venue (April 22, 2018)",NaN,32387059,"{'city': 'Belfast, UK', 'lat': 54.597285, 'lng...","[{'billing': 'headline', 'displayName': 'Holot...",0.000002,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/32387059-holo...,"{'displayName': 'Unknown venue', 'lat': 54.597..."
1,None,"Nada Surf at Limelight 2 (April 22, 2018)",NaN,32628004,"{'city': 'Belfast, UK', 'lat': 54.5935125, 'ln...","[{'displayName': 'Nada Surf', 'billingIndex': ...",0.050197,NaN,"{'datetime': '2018-04-22T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32628004-nada...,"{'displayName': 'Limelight 2', 'lat': 54.59351..."
2,None,"Black Doldrums at Unknown venue (April 22, 2018)",NaN,33204699,"{'city': 'Belfast, UK', 'lat': 54.597285, 'lng...","[{'displayName': 'Black Doldrums', 'billingInd...",0.000034,NaN,"{'datetime': '2018-04-22T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33204699-blac...,"{'displayName': 'Unknown venue', 'lat': 54.597..."
0,None,Rumours Of Fleetwood Mac at Birmingham Town Ha...,NaN,31536879,"{'lat': 52.4792656, 'lng': -1.9029918, 'city':...","[{'billingIndex': 1, 'billing': 'headline', 'a...",0.000201,NaN,"{'datetime': '2018-04-13T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31536879-rumo...,"{'lat': 52.4792656, 'metroArea': {'country': {..."
1,None,"The Neville Staple Band with Stranger Cole, Th...",NaN,31722464,"{'city': 'Birmingham, UK', 'lat': 52.4743255, ...","[{'displayName': 'The Neville Staple Band', 'b...",0.001266,NaN,"{'datetime': '2018-04-13T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31722464-nevi...,"{'displayName': 'O2 Academy 2 Birmingham', 'la..."
2,None,"Dancing on Ice at Arena Birmingham (April 13, ...",NaN,31989179,"{'city': 'Birmingham, UK', 'lat': 52.4826511, ...","[{'displayName': 'Dancing on Ice', 'billingInd...",0.000004,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/31989179-danc...,"{'displayName': 'Arena Birmingham', 'lat': 52...."
3,None,The Virginmarys at The Actress & Bishop (April...,NaN,32546519,"{'city': 'Birmingham, UK', 'lat': 52.4844186, ...","[{'displayName': 'The Virginmarys', 'billingIn...",0.007775,NaN,"{'datetime': '2018-04-13T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32546519-virg...,"{'displayName': 'The Actress & Bishop', 'lat':..."
4,None,"NOT3S at O2 Institute2 Birmingham (April 13, 2...",NaN,32576614,"{'city': 'Digbeth, UK', 'lat': 52.4759918, 'ln...","[{'displayName': 'NOT3S', 'billingIndex': 1, '...",0.004997,NaN,"{'datetime': '2018-04-13T18:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32576614-not3...,"{'displayName': 'O2 Institute2 Birmingham', 'l..."
5,None,Jumanji with Bare Traps and Quinn at Sunflower...,NaN,32675914,"{'city': 'Birmingham, UK', 'lat': 52.4761884, ...","[{'displayName': 'Jumanji', 'billingIndex': 1,...",0.001089,NaN,"{'datetime': '2018-04-13T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32675914-juma...,"{'displayName': 'Sunflower Lounge', 'lat': 52...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,None,"Laish at The Cumberland Arms (April 19, 2018)",NaN,31976829,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Laish', 'billingIndex': 1, '...",0.000596,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31976829-lais...,"{'displayName': 'The Cumberland Arms', 'lat': ..."
1,None,Funke and the Two Tone Baby at The Cluny 2 (Ap...,NaN,32224619,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....",[{'displayName': 'Funke and the Two Tone Baby'...,0.000132,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32224619-funk...,"{'displayName': 'The Cluny 2', 'lat': 54.97492..."
2,None,"The Undercover Hippy at Bar Loco (April 19, 2018)",NaN,32469174,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'billing': 'headline', 'displayName': 'The U...",0.000617,NaN,"{'datetime': '2018-04-19T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32469174-unde...,"{'displayName': 'Bar Loco', 'lat': 54.9755475,..."
3,None,"The Virginmarys at Think Tank? (April 19, 2018)",NaN,32642734,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'The Virginmarys', 'billingIn...",0.007605,NaN,"{'datetime': '2018-04-19T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32642734-virg...,"{'displayName': 'Think Tank?', 'lat': 54.96794..."
4,None,"Nick J.D. Hodgson at Cobalt Studios (April 19,...",NaN,32769839,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Nick J.D. Hodgson', 'billing...",0.000062,NaN,"{'datetime': '2018-04-19T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32769839-nick...,"{'displayName': 'Cobalt Studios', 'lat': 54.97..."
5,None,"The Homesick at Little Buildings (April 19, 2018)",NaN,32952039,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'The Homesick', 'billingIndex...",0.000000,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/32952039-home...,"{'displayName': 'Little Buildings', 'lat': 54...."
6,None,"KIOKO at Northumbria Institute (April 19, 2018)",NaN,33023799,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'KIOKO', 'billingIndex': 1, '...",0.000083,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33023799-kiok...,"{'displayName': 'Northumbria Institute', 'lat'..."
7,None,"Graces (UK) at Nemix (April 19, 2018)",NaN,33180549,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Graces (UK)', 'billingIndex'...",0.000001,NaN,"{'datetime': '2018-04-19T19:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33180549-grac...,"{'displayName': 'Nemix', 'lat': 54.970323, 'ln..."
0,None,"Gengahr at Think Tank? (April 21, 2018)",NaN,31658739,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Gengahr', 'billingIndex': 1,...",0.005804,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31658739-geng...,"{'displayName': 'Think Tank?', 'lat': 54.96794..."
1,None,"Lilly Hiatt at The Cluny 2 (April 21, 2018)",NaN,31723839,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'billing': 'headline', 'billingIndex': 1, 'a...",0.000388,NaN,"{'datetime': '2018-04-21T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31723839-lill...,{'metroArea': {'displayName': 'Newcastle Upon ...
2,None,Little Comets at O2 Academy Newcastle (April 2...,NaN,31921799,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'billing': 'headline', 'displayName': 'Littl...",0.020176,NaN,"{'datetime': '2018-04-21T18:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/31921799-litt...,"{'displayName': 'O2 Academy Newcastle', 'lat':..."
3,None,Koo Koo Kanga Roo and MC Lars with A New Nowhe...,NaN,32449254,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Koo Koo Kanga Roo', 'billing...",0.006655,NaN,"{'datetime': '2018-04-21T18:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32449254-koo-...,"{'displayName': 'O2 Academy 2 Newcastle', 'lat..."
4,None,Black Water County at Jumpin' Jack's (April 21...,NaN,32506094,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Black Water County', 'billin...",0.000036,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",cancelled,Concert,http://www.songkick.com/concerts/32506094-blac...,"{'displayName': 'Jumpin' Jack's', 'lat': 54.96..."
5,None,InVisions with Misanthropy and Perceptions at ...,NaN,32768294,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'InVisions', 'billingIndex': ...",0.000155,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32768294-invi...,"{'displayName': 'Little Buildings', 'lat': 54...."
6,None,"We Are Not Devo at The Cluny (April 21, 2018)",NaN,32808974,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'We Are Not Devo', 'billingIn...",0.000007,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32808974-we-a...,"{'displayName': 'The Cluny', 'lat': 54.9749282..."
7,None,"Wayward Sons at Riverside (April 21, 2018)",NaN,32840199,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Wayward Sons', 'billingIndex...",0.000178,NaN,"{'datetime': '2018-04-21T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32840199-wayw...,"{'displayName': 'Riverside', 'lat': 54.9683416..."
8,None,Canny Fringe Presents: Third Time Lucky Festiv...,"{'datetime': None, 'time': None, 'date': '2018...",33230574,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Shanghai Blues', 'billingInd...",0.000033,{'displayName': 'Canny Fringe Presents: Third ...,"{'datetime': None, 'time': None, 'date': '2018...",ok,Festival,http://www.songkick.com/festivals/2300294-cann...,"{'displayName': 'Unknown venue', 'lat': 54.978..."
9,None,Sam Dickinson at North of England Institute of...,NaN,33308534,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Sam Dickinson', 'billingInde...",0.000011,NaN,"{'datetime': '2018-04-21T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33308534-sam-...,{'displayName': 'North of England Institute of...
10,None,"FUTURE LOVE at Digital (April 21, 2018)",NaN,33326339,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'FUTURE LOVE', 'billingIndex'...",0.000016,NaN,"{'datetime': '2018-04-21T22:30:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/33326339-futu...,"{'displayName': 'Digital', 'lat': 54.9678494, ..."
11,None,Slurs (UK) and Baker Island at RPM Records (Ap...,NaN,33497549,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Slurs (UK)', 'billingIndex':...",0.000049,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/33497549-slur...,"{'displayName': 'RPM Records', 'lat': None, 'l..."
12,None,"Badger (UK) at The Cumberland Arms (April 21, ...",NaN,33507774,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Badger (UK)', 'billingIndex'...",0.000000,NaN,"{'datetime': None, 'time': None, 'date': '2018...",ok,Concert,http://www.songkick.com/concerts/33507774-badg...,"{'displayName': 'The Cumberland Arms', 'lat': ..."
0,None,Last Great Dreamers at Trillians Rock Bar (Apr...,NaN,32388384,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'billing': 'headline', 'displayName': 'Last ...",0.000031,NaN,"{'datetime': '2018-04-22T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32388384-last...,"{'displayName': 'Trillians Rock Bar', 'lat': 5..."
1,None,Ian Siegal with The Dawn Brothers at Sage Gate...,NaN,32564524,"{'city': 'Gateshead, UK', 'lat': 54.9672729, '...","[{'billing': 'headline', 'displayName': 'Ian S...",0.000641,NaN,"{'datetime': '2018-04-22T20:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32564524-ian-...,"{'displayName': 'Sage Gateshead', 'lat': 54.96..."
2,None,"Raintown at The Cluny 2 (April 22, 2018)",NaN,32593289,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Raintown', 'billingIndex': 1...",0.000140,NaN,"{'datetime': '2018-04-22T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32593289-rain...,"{'displayName': 'The Cluny 2', 'lat': 54.97492..."
3,None,Frank Turner with Frank Turner & The Sleeping ...,NaN,32642214,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Frank Turner', 'billingIndex...",0.048988,NaN,"{'datetime': '2018-04-22T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32642214-fran...,"{'displayName': 'O2 Academy Newcastle', 'lat':..."
4,None,"Thomas Truax at The Cumberland Arms (April 22,...",NaN,32931109,"{'city': 'Newcastle Upon Tyne, UK', 'lat': 54....","[{'displayName': 'Thomas Truax', 'billingIndex...",0.000385,NaN,"{'datetime': '2018-04-22T19:00:00+0100', 'time...",ok,Concert,http://www.songkick.com/concerts/32931109-thom...,"{'displayName': 'The Cumberland Arms', 'lat': ..."